import Navbar from '@/components/shared/Navbar';
import React from 'react';


export const metadata = {
  title: "Dragon News",
  description: "Generated by create next app",
};
const AuthLayout = ({ children }) => {
    return (
        <div>
            <Navbar></Navbar>
            {children}
        </div>
    );
};

export default AuthLayout;