import React from 'react';


export const metadata = {
  title: "Dragon News | Register",
  description: "Generated by create next app",
};
const RegisterPage = () => {
    return (
        <div>
            register page
        </div>
    );
};

export default RegisterPage;