import React from 'react';

export const metadata = {
  title: "Dragon News | Login",
  description: "Generated by create next app",
};
const LoginPage = () => {
    return (
        <div>
            login page
        </div>
    );
};

export default LoginPage;